<template>
  <div class="modal fade" id="privacy-policy" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">سياسات الخصوصية</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>توضح سياسة الخصوصية هذه كيف نجمع معلوماتك ونستخدمها ونفصح عنها ونحميها عندما تزور موقعنا على الويب [وتطبيقاتنا للجوال] ، بما في ذلك أي نموذج وسائط آخر أو قناة وسائط أو موقع ويب للجوال أو تطبيق جوال مرتبط أو متصل بها (مجتمعة &quot;الموقع&quot;). يرجى قراءة سياسة الخصوصية بعناية. إذا كنت لا توافق على شروط سياسة الخصوصية هذه ، يرجى عدم الوصول إلى الموقع.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحتفظ بالحق في إجراء تغييرات على سياسة الخصوصية هذه في أي وقت ولأي سبب. سننبهك بشأن أي تغييرات عن طريق تحديث تاريخ &quot;آخر تحديث&quot; لسياسة الخصوصية هذه. ستصبح أي تغييرات أو تعديلات سارية فور نشر سياسة الخصوصية المحدثة على الموقع ، وتتنازل عن الحق في تلقي إشعار محدد لكل تغيير أو تعديل.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نشجعك على مراجعة سياسة الخصوصية هذه بشكل دوري للبقاء على اطلاع على التحديثات. سيتم اعتبار أنك قد تم إعلامك بها ، وستكون خاضعًا لها ، وسيتم قبولك للتغييرات في أي سياسة خصوصية تمت مراجعتها من خلال استمرار استخدامك للموقع بعد تاريخ نشر سياسة الخصوصية المنقحة هذه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>جمع معلوماتك</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نجمع معلومات عنك بطرق متنوعة. تتضمن المعلومات التي قد نجمعها على الموقع ما يلي:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>بيانات شخصية</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>معلومات التعريف الشخصية ، مثل اسمك وعنوان الشحن وعنوان البريد الإلكتروني ورقم الهاتف والمعلومات الديموغرافية مثل عمرك وجنسك ومدينتك واهتماماتك التي تقدمها لنا طوعًا عند التسجيل في الموقع أو الهاتف المحمول الخاص بنا التطبيق ، أو عندما تختار المشاركة في الأنشطة المختلفة المتعلقة بالموقع [وتطبيقات الهاتف المحمول لدينا ، مثل الدردشة عبر الإنترنت ولوحات الرسائل. أنت غير ملزم بتزويدنا بمعلومات شخصية من أي نوع ، ولكن رفضك للقيام بذلك قد يمنعك من استخدام ميزات معينة من الموقع وتطبيقات الهاتف المحمول الخاصة بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>البيانات المشتقة</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>المعلومات التي تجمعها خوادمنا تلقائيًا عند دخولك إلى الموقع ، مثل عنوان&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>IP</span><span style='font-family:"Arial",sans-serif;'>&nbsp;الخاص بك ونوع المتصفح ونظام التشغيل وأوقات الوصول والصفحات التي شاهدتها مباشرة قبل الوصول إلى الموقع وبعده. إذا كنت تستخدم تطبيق الهاتف المحمول الخاص بنا ، فقد تتضمن هذه المعلومات أيضًا اسم جهازك ونوعه ونظام التشغيل ورقم هاتفك وبلدك وإعجاباتك والردود على مشاركة والتفاعلات الأخرى مع التطبيق والمستخدمين الآخرين عبر سجل الخادم الملفات ، بالإضافة إلى أي معلومات أخرى تختار تقديمها.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>البيانات المالية</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>المعلومات المالية ، مثل البيانات المتعلقة بطريقة الدفع الخاصة بك ، والتي قد نجمعها عند الشراء أو الطلب أو الإرجاع أو التبادل أو طلب معلومات حول خدماتنا من الموقع أو تطبيق الهاتف المحمول الخاص بنا. نقوم بتخزين المعلومات المالية المحدودة للغاية ، إن وجدت ، التي نجمعها. خلاف ذلك ، يتم تخزين جميع المعلومات المالية بواسطة معالج الدفع الخاص بنا ، ونشجعك على مراجعة سياسة الخصوصية الخاصة بهم والاتصال بهم مباشرة للرد على أسئلتك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>أذونات&nbsp;</span></strong><strong><span dir="LTR" style='font-size:20px;font-family:"Arial",sans-serif;'>Facebook</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يجوز للموقع وتطبيقات الجوال الخاصة بنا الوصول بشكل افتراضي إلى حسابك&nbsp;</span><a href="https://www.facebook.com/about/privacy/" target="_blank"><span style='font-family:"Arial",sans-serif;'>الأساسي على&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Facebook</span></a>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>المعلومات ، بما في ذلك الاسم والبريد الإلكتروني والجنس وتاريخ الميلاد والمدينة الحالية وعنوان&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>URL</span><span style='font-family:"Arial",sans-serif;'>&nbsp;لصورة الملف الشخصي ، بالإضافة إلى المعلومات الأخرى التي تختار نشرها للجمهور. قد نطلب أيضًا الوصول إلى أذونات أخرى تتعلق بحسابك ، مثل الأصدقاء ، وعمليات تسجيل الوصول ، وإبداءات الإعجاب ، ويمكنك اختيار منحنا أو منعنا من الوصول إلى كل إذن فردي. لمزيد من المعلومات حول&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Facebook</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أذونات ، راجع&nbsp;</span><a href="https://developers.facebook.com/docs/facebook-login/permissions" target="_blank"><span style='font-family:"Arial",sans-serif;'>صفحة مرجع أذونات&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Facebook.</span></a>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>البيانات من الشبكات الاجتماعية</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>معلومات المستخدم من مواقع الشبكات الاجتماعية ، مثل مركز ألعاب&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Apple</span><span style='font-family:"Arial",sans-serif;'>&nbsp;و&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Facebook</span><span style='font-family:"Arial",sans-serif;'>&nbsp;و&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Google+&nbsp;</span><span style='font-family:"Arial",sans-serif;'>و&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Instagram</span><span style='font-family:"Arial",sans-serif;'>&nbsp;و&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Pinterest</span><span style='font-family:"Arial",sans-serif;'>&nbsp;و&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Twitter</span><span style='font-family:"Arial",sans-serif;'>&nbsp;، بما في ذلك اسمك واسم مستخدم الشبكة الاجتماعية والموقع والجنس وتاريخ الميلاد وعنوان البريد الإلكتروني وصورة الملف الشخصي والبيانات العامة لـ جهات الاتصال ، إذا قمت بربط حسابك بهذه الشبكات الاجتماعية. إذا كنت تستخدم تطبيق الهاتف المحمول الخاص بنا ، فقد تتضمن هذه المعلومات أيضًا معلومات الاتصال لأي شخص تدعوه لاستخدامه و / أو الانضمام إلى تطبيق الهاتف المحمول الخاص بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>بيانات الجهاز المحمول</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>معلومات الجهاز ، مثل معرف الجهاز المحمول الخاص بك والطراز والشركة المصنعة ، ومعلومات حول موقع جهازك ، إذا قمت بالوصول إلى الموقع من جهاز محمول.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>بيانات الطرف الثالث</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>معلومات من أطراف ثالثة ، مثل المعلومات الشخصية أو أصدقاء الشبكة ، إذا قمت بربط حسابك بالطرف الثالث ومنحت الموقع الإذن للوصول إلى هذه المعلومات.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>بيانات من المسابقات والهبات والاستطلاعات</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>المعلومات الشخصية وغيرها من المعلومات التي قد تقدمها عند الدخول في المسابقات أو الهدايا و / أو الرد على الاستبيانات.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>معلومات تطبيقات الهاتف المحمول</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا قمت بالاتصال باستخدام تطبيق الهاتف المحمول الخاص بنا:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● معلومات الموقع الجغرافي. قد نطلب الوصول أو الإذن إلى المعلومات المستندة إلى الموقع وتتبعها من جهازك المحمول ، إما بشكل مستمر أو أثناء استخدامك لتطبيق الهاتف المحمول الخاص بنا ، لتقديم خدمات تستند إلى الموقع. إذا كنت ترغب في تغيير وصولنا أو أذوناتنا ، فيمكنك القيام بذلك في إعدادات جهازك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● الوصول إلى الجهاز المحمول. قد نطلب الوصول أو الإذن بميزات معينة من جهازك المحمول ، بما في ذلك البلوتوث والتقويم والكاميرا وجهات الاتصال والميكروفون والتذكيرات وأجهزة الاستشعار ورسائل&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>SMS</span><span style='font-family:"Arial",sans-serif;'>&nbsp;وحسابات الوسائط الاجتماعية والتخزين وميزات أخرى على جهازك المحمول] وغيرها من الميزات. إذا كنت ترغب في تغيير وصولنا أو أذوناتنا ، فيمكنك القيام بذلك في إعدادات جهازك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● بيانات الجهاز المحمول. قد نقوم بجمع معلومات الجهاز (مثل معرف الجهاز المحمول الخاص بك والطراز والشركة المصنعة) ونظام التشغيل ومعلومات الإصدار وعنوان&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>IP.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● دفع الإخطارات. قد نطلب أن نرسل لك إشعارات الدفع المتعلقة بحسابك أو التطبيق. إذا كنت ترغب في إلغاء الاشتراك من تلقي هذه الأنواع من الاتصالات ، فيمكنك إيقاف تشغيلها في إعدادات جهازك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>استخدام معلوماتك</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إن الحصول على معلومات دقيقة عنك يسمح لنا بتزويدك بتجربة سلسة وفعالة ومخصصة. على وجه التحديد ، قد نستخدم المعلومات التي تم جمعها عنك عبر الموقع أو تطبيق الهاتف المحمول لدينا من أجل:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● إدارة الباقات والعروض الترويجية والمسابقات.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● مساعدة إنفاذ القانون والرد على أمر الاستدعاء.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● تجميع بيانات إحصائية وتحليل مجهول للاستخدام داخليا أو مع أطراف ثالثة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● إنشاء وإدارة حسابك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● قم بتسليم إعلانات مستهدفة وكوبونات ونشرات إخبارية ومعلومات أخرى تتعلق بالعروض الترويجية والموقع وتطبيقات الهاتف المحمول الخاصة بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● مراسلتك عبر البريد الإلكتروني بخصوص حسابك أو طلبك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● تمكين اتصالات المستخدم.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● تنفيذ وإدارة المشتريات والأوامر والمدفوعات والمعاملات الأخرى المتعلقة بالموقع وتطبيقات الهاتف المحمول لدينا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● إنشاء ملف تعريف شخصي عنك لجعل الزيارات المستقبلية للموقع وتطبيقات الهاتف المحمول الخاصة بنا أكثر تخصيصًا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● زيادة كفاءة وتشغيل الموقع وتطبيقات الهاتف المحمول.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● مراقبة وتحليل الاستخدام والاتجاهات لتحسين تجربتك مع الموقع وتطبيق الهاتف المحمول الخاص بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● يخطرك بتحديثات الموقع وتطبيقات الهاتف المحمول الخاصة بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● تقديم منتجات وخدمات و / أو تطبيقات و / أو توصيات جديدة لك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● أداء الأنشطة التجارية الأخرى حسب الحاجة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● منع المعاملات الاحتيالية ، ومراقبة السرقة ، والحماية من النشاط الإجرامي.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● معالجة المدفوعات والمبالغ المستردة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● اطلب التغذية المرتدة واتصل بك بشأن استخدامك للموقع وتطبيقات الهاتف المحمول الخاصة بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● حل النزاعات واستكشاف الأخطاء وإصلاحها.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● الرد على طلبات المنتج وخدمة العملاء.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● أرسل لك رسالة إخبارية.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● التماس الدعم للموقع وتطبيقات الهاتف المحمول لدينا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● أخرى</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>الكشف عن معلوماتك</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نشارك المعلومات التي قمنا بجمعها عنك في مواقف معينة. قد يتم الكشف عن معلوماتك على النحو التالي:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>بموجب القانون أو لحماية الحقوق</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا كنا نعتقد أن نشر معلومات عنك أمر ضروري للرد على الإجراءات القانونية ، أو للتحقيق في الانتهاكات المحتملة لسياساتنا أو علاجها ، أو لحماية حقوق الآخرين وممتلكاتهم وسلامتهم ، فقد نشارك معلوماتك على النحو المسموح به أو المطلوب من قبل أي قانون أو قاعدة أو لائحة سارية. وهذا يشمل تبادل المعلومات مع الكيانات الأخرى للحماية من الاحتيال والحد من مخاطر الائتمان.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>مقدمو خدمة الطرف الثالث</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نشارك معلوماتك مع أطراف ثالثة تقدم خدمات لنا أو بالنيابة عنا ، بما في ذلك معالجة الدفع ، وتحليل البيانات ، وتسليم البريد الإلكتروني ، وخدمات الاستضافة ، وخدمة العملاء ، والمساعدة في التسويق.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>الاتصالات التسويقية</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>بموافقتك ، أو مع فرصة لك لسحب الموافقة ، قد نشارك معلوماتك مع أطراف ثالثة لأغراض تسويقية ، على النحو الذي يسمح به القانون.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>التفاعل مع المستخدمين الآخرين</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا كنت تتفاعل مع مستخدمين آخرين للموقع وتطبيقنا للجوال ، فقد يرى هؤلاء المستخدمون اسمك وصورة ملفك الشخصي وأوصاف نشاطك ، بما في ذلك إرسال دعوات إلى مستخدمين آخرين ، والدردشة مع مستخدمين آخرين ، وإبداء الإعجاب بالمشاركات ، ومتابعة المدونات.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>التعيينات عبر الإنترنت</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>عندما تقوم بنشر تعليقات أو مساهمات أو محتوى آخر على الموقع أو تطبيقات الهاتف المحمول الخاصة بنا ، فقد يتم عرض مشاركاتك من قبل جميع المستخدمين وقد يتم توزيعها علنًا خارج الموقع وتطبيقات الجوال الخاصة بنا إلى الأبد.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>معلنو الطرف الثالث</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نستخدم شركات إعلانات خارجية لخدمة الإعلانات عند زيارة الموقع أو تطبيق الهاتف المحمول الخاص بنا. قد تستخدم هذه الشركات معلومات حول زياراتك إلى الموقع وتطبيقاتنا للجوال ومواقع الويب الأخرى المضمنة في ملفات تعريف ارتباط الويب من أجل تقديم إعلانات حول السلع والخدمات التي تهمك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>الشركات التابعة</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نشارك معلوماتك مع الشركات التابعة لنا ، وفي هذه الحالة سنطلب من تلك الشركات التابعة احترام سياسة الخصوصية هذه. تشمل الشركات التابعة شركتنا الأم وأي شركات تابعة أو شركاء في المشاريع المشتركة أو شركات أخرى نسيطر عليها أو تخضع لسيطرة مشتركة معنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>شركاء العمل</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نشارك معلوماتك مع شركائنا التجاريين لنقدم لك بعض المنتجات أو الخدمات أو العروض الترويجية.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>عرض الحائط</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد يعرض تطبيقنا للجوال &quot;جدار عرض&quot; مستضاف من جهة خارجية. يسمح جدار العرض هذا للمعلنين الخارجيين بتقديم عملة افتراضية أو هدايا أو عناصر أخرى للمستخدمين مقابل قبول وإكمال عرض إعلاني. قد يظهر جدار العرض هذا في تطبيق الهاتف المحمول الخاص بنا ويتم عرضه لك بناءً على بيانات معينة ، مثل منطقتك الجغرافية أو المعلومات الديموغرافية. عندما تنقر على حائط العرض ، ستترك تطبيق الهاتف المحمول الخاص بنا. ستتم مشاركة معرّف فريد ، مثل معرف المستخدم الخاص بك ، مع مزود جدار العرض من أجل منع الاحتيال وإضافتها إلى حسابك بشكل صحيح.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>اتصالات وسائل التواصل الاجتماعي</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا قمت بالاتصال بالموقع أو تطبيق الهاتف المحمول الخاص بنا من خلال شبكة اجتماعية ، فسوف ترى جهات الاتصال الخاصة بك على الشبكة الاجتماعية اسمك وصورة ملفك الشخصي وأوصاف نشاطك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>الأطراف الثالثة الأخرى</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نشارك معلوماتك مع المعلنين والمستثمرين بغرض إجراء تحليل عام للأعمال. يجوز لنا أيضًا مشاركة معلوماتك مع هذه الأطراف الثالثة لأغراض التسويق ، وفقًا لما يسمح به القانون.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-family:"Arial",sans-serif;'>البيع أو الإفلاس</span></strong>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا أعدنا تنظيم أو بيع كل أو جزء من أصولنا أو خضعت لعملية اندماج أو حصلنا عليها من قبل كيان آخر ، فقد ننقل معلوماتك إلى الكيان اللاحق. إذا خرجنا من العمل أو دخلنا في الإفلاس ، فستكون معلوماتك من الأصول التي تم نقلها أو الحصول عليها من قبل طرف ثالث. أنت تقر بأن عمليات النقل هذه قد تحدث وأن الشخص المنقول إليه قد يرفض التزامات الشرف التي قطعناها على أنفسنا في سياسة الخصوصية هذه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحن لسنا مسؤولين عن تصرفات الأطراف الثالثة التي تشارك معها بيانات شخصية أو حساسة ، وليس لدينا أي سلطة لإدارة أو السيطرة على طلبات الطرف الثالث. إذا لم تعد ترغب في تلقي المراسلات أو رسائل البريد الإلكتروني أو الاتصالات الأخرى من أطراف ثالثة ، فأنت مسؤول عن الاتصال بالطرف الثالث مباشرة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>تقنيات التتبع</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>ملفات تعريف الارتباط وإشارات الويب</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نستخدم ملفات تعريف الارتباط وإشارات الويب ووحدات بكسل التتبع وتقنيات التتبع الأخرى على الموقع وتطبيق الهاتف المحمول الخاص بنا] للمساعدة في تخصيص الموقع وتطبيقنا للجوال وتحسين تجربتك. عندما تدخل إلى الموقع [أو تطبيق الهاتف المحمول الخاص بنا ، فأنت شخصي</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يتم جمع المعلومات من خلال استخدام تقنية التتبع. يتم تعيين معظم المتصفحات لقبول ملفات تعريف الارتباط بشكل افتراضي. يمكنك إزالة ملفات تعريف الارتباط أو رفضها ، ولكن كن على دراية بأن مثل هذا الإجراء يمكن أن يؤثر على توفر ووظائف الموقع [أو تطبيق الهاتف المحمول الخاص بنا. لا يجوز لك رفض إشارات الويب. ومع ذلك ، يمكن جعلها غير فعالة عن طريق رفض جميع ملفات تعريف الارتباط أو عن طريق تعديل إعدادات متصفح الويب الخاص بك لإعلامك في كل مرة يتم فيها تقديم ملف تعريف الارتباط ، مما يسمح لك بقبول ملفات تعريف الارتباط أو رفضها على أساس فردي.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نستخدم ملفات تعريف الارتباط وإشارات الويب ووحدات بكسل التتبع وغير ذلك من تقنيات التتبع على الموقع وتطبيق الهاتف المحمول الخاص بنا للمساعدة في تخصيص الموقع وتطبيق الهاتف المحمول وتحسين تجربتك. لمزيد من المعلومات حول كيفية استخدامنا لملفات تعريف الارتباط ، يرجى الرجوع إلى سياسة ملفات تعريف الارتباط المنشورة على الموقع ، والتي تم دمجها في سياسة الخصوصية هذه. باستخدام هذا الموقع ، فإنك توافق على الالتزام بسياسة ملفات تعريف الارتباط.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>[عدل]</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>الإعلان عبر الإنترنت</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>بالإضافة إلى ذلك ، يجوز لنا استخدام برنامج تابع لجهة خارجية لعرض الإعلانات على الموقع [وتطبيقاتنا للجوال] ، وتنفيذ حملات التسويق عبر البريد الإلكتروني ، وإدارة مبادرات التسويق التفاعلية الأخرى. قد يستخدم برنامج الجهة الخارجية هذا ملفات تعريف الارتباط أو تقنية تتبع مشابهة للمساعدة في إدارة تجربتك عبر الإنترنت وتحسينها معنا. لمزيد من المعلومات حول إلغاء الاشتراك في الإعلانات التي تستهدف الاهتمامات ، تفضل بزيارة أداة إلغاء&nbsp;</span><a href="http://www.networkadvertising.org/choices/" target="_blank"><span style='font-family:"Arial",sans-serif;'>الاشتراك في مبادرة الإعلانات على الشبكة أو أداة</span></a><span style='font-family:"Arial",sans-serif;'>&nbsp;إلغاء&nbsp;</span><a href="http://www.networkadvertising.org/choices/" target="_blank"><span style='font-family:"Arial",sans-serif;'>الاشتراك في</span></a><span style='font-family:"Arial",sans-serif;'>&nbsp;</span><a href="http://www.aboutads.info/choices/" target="_blank"><span style='font-family:"Arial",sans-serif;'>تحالف الإعلانات الرقمية.</span></a>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>تحليلات الموقع</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نقوم أيضًا بالشراكة مع بائع من جهة خارجية مختارة ، والسماح بتقنيات التتبع وخدمات إعادة التسويق على الموقع وتطبيق الهاتف المحمول الخاص بنا من خلال استخدام ملفات تعريف ارتباط الطرف الأول وملفات تعريف ارتباط الطرف الثالث ، من بين أمور أخرى ، لتحليل وتتبع المستخدمين &quot; استخدام الموقع وتطبيقات الهاتف المحمول الخاصة بنا ، وتحديد شعبية محتوى معين وفهم النشاط عبر الإنترنت بشكل أفضل. من خلال الوصول إلى الموقع أو تطبيق الهاتف المحمول الخاص بنا ، فإنك توافق على جمع واستخدام معلوماتك من قبل هؤلاء الموردين الخارجيين. نشجعك على مراجعة سياسة الخصوصية الخاصة بهم والاتصال بهم مباشرة للرد على أسئلتك. نحن لا ننقل المعلومات الشخصية إلى هؤلاء الموردين الخارجيين. ومع ذلك ، إذا كنت لا تريد أن يتم جمع أي معلومات واستخدامها بواسطة تقنيات التتبع.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يجب أن تدرك أن الحصول على جهاز كمبيوتر جديد ، أو تثبيت متصفح جديد ، أو ترقية متصفح موجود ، أو محو ملفات تعريف الارتباط الخاصة بالمستعرض أو تغييرها قد يؤدي أيضًا إلى مسح بعض ملفات تعريف الارتباط للتعطيل ، أو المكونات الإضافية ، أو الإعدادات.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>مواقع الطرف الثالث</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد يحتوي الموقع [وتطبيقاتنا للجوال] على روابط لمواقع وتطبيقات خارجية ذات أهمية ، بما في ذلك الإعلانات والخدمات الخارجية ، التي لا تنتمي إلينا. بمجرد استخدامك لهذه الروابط لمغادرة الموقع أو تطبيق الهاتف المحمول الخاص بنا ، فإن أي معلومات تقدمها إلى هذه الأطراف الثالثة لا تغطيها سياسة الخصوصية هذه ، ولا يمكننا ضمان سلامة وخصوصية معلوماتك. قبل زيارة وتقديم أي معلومات إلى أي مواقع ويب لأطراف ثالثة ، يجب عليك إبلاغ نفسك بسياسات وممارسات الخصوصية (إن وجدت) الخاصة بالطرف الثالث المسؤول عن هذا الموقع ، ويجب عليك اتخاذ هذه الخطوات اللازمة ، وفقًا لتقديرك ، لحماية خصوصية معلوماتك. نحن لسنا مسؤولين عن المحتوى أو ممارسات وسياسات الخصوصية والأمن لأي أطراف ثالثة ، بما في ذلك المواقع أو الخدمات أو التطبيقات الأخرى التي قد تكون مرتبطة بالموقع أو من الموقع أو تطبيق الهاتف المحمول الخاص بنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>أمن معلوماتك</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نستخدم إجراءات الأمان الإدارية والفنية والمادية للمساعدة في حماية معلوماتك الشخصية. على الرغم من أننا اتخذنا خطوات معقولة لتأمين المعلومات الشخصية التي تقدمها لنا ، يرجى الانتباه إلى أنه على الرغم من جهودنا ، لا توجد تدابير أمنية مثالية أو لا يمكن اختراقها ، ولا يمكن ضمان أي طريقة لنقل البيانات ضد أي اعتراض أو أي نوع آخر من سوء الاستخدام. أي معلومات تم الكشف عنها عبر الإنترنت عرضة للاعتراض وإساءة الاستخدام من قبل أطراف غير مصرح بها. لذلك ، لا يمكننا ضمان الأمن الكامل إذا قدمت معلومات شخصية.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>سياسة الأطفال</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحن لا نطلب عن قصد معلومات أو تسويق للأطفال دون سن العاشرة. إذا علمت بأية بيانات قمنا بجمعها من الأطفال تحت سن 10 سنوات ، يرجى الاتصال بنا باستخدام معلومات الاتصال المقدمة أدناه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>ضوابط لميزات لا تتبع</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>تتضمن معظم متصفحات الويب وبعض أنظمة تشغيل الجوال [وتطبيقاتنا المحمولة] ميزة عدم التتبع (&quot;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>DNT&quot;)&nbsp;</span><span style='font-family:"Arial",sans-serif;'>أو الإعداد الذي يمكنك تنشيطه للإشارة إلى تفضيل الخصوصية الخاص بك لعدم وجود بيانات حول أنشطة التصفح عبر الإنترنت الخاصة بك والتي يتم رصدها وجمعها. لم يتم الانتهاء من أي معيار تقني موحد للتعرف على إشارات&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>DNT</span><span style='font-family:"Arial",sans-serif;'>&nbsp;وتنفيذها. على هذا النحو ، نحن لا نستجيب حاليًا لإشارات متصفح&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>DNT</span><span style='font-family:"Arial",sans-serif;'>&nbsp;أو أي آلية أخرى تقوم تلقائيًا بإبلاغ اختيارك بعدم التتبع عبر الإنترنت. إذا تم اعتماد معيار للتتبع عبر الإنترنت يجب أن نتبعه في المستقبل ، فسنبلغك بهذه الممارسة في نسخة معدلة من سياسة الخصوصية هذه. -ميزة عدم التتبع (</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>DNT)&nbsp;</span><span style='font-family:"Arial",sans-serif;'>أو الإعداد الذي يمكنك تنشيطه للإشارة إلى تفضيل الخصوصية الخاص بك لعدم وجود بيانات حول أنشطة التصفح عبر الإنترنت الخاصة بك يتم رصدها وجمعها. إذا قمت بتعيين إشارة&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>DNT</span><span style='font-family:"Arial",sans-serif;'>&nbsp;على متصفحك ، فسنستجيب لإشارات متصفح&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>DNT.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>خيارات بخصوص معلوماتك</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>[معلومات الحساب]</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يمكنك في أي وقت مراجعة أو تغيير المعلومات في حسابك أو إنهاء حسابك</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>بواسطة:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● تسجيل الدخول إلى إعدادات حسابك وتحديث حسابك</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● الاتصال بنا باستخدام معلومات الاتصال الواردة أدناه</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● [أخرى]</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>بناء على طلبك لإنهاء حسابك ، سنقوم بتعطيل أو حذف حسابك ومعلوماتك من قواعد بياناتنا النشطة. ومع ذلك ، قد يتم الاحتفاظ ببعض المعلومات في ملفاتنا لمنع الاحتيال واستكشاف المشكلات وإصلاحها والمساعدة في أي تحقيقات وإنفاذ شروط الاستخدام و / أو الامتثال للمتطلبات القانونية.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>رسائل البريد الإلكتروني والاتصالات</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا لم تعد ترغب في تلقي مراسلات أو رسائل بريد إلكتروني أو اتصالات أخرى منا ، فيمكنك إلغاء الاشتراك من خلال:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● ملاحظة تفضيلاتك في الوقت الذي تقوم فيه بتسجيل حسابك في الموقع [أو تطبيق الجوال لدينا]</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● تسجيل الدخول إلى إعدادات حسابك وتحديث تفضيلاتك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>● الاتصال بنا باستخدام معلومات الاتصال الواردة أدناه</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا لم تعد ترغب في تلقي المراسلات أو رسائل البريد الإلكتروني أو الاتصالات الأخرى من أطراف ثالثة ، فأنت مسؤول عن الاتصال بالطرف الثالث مباشرة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:right;'><span dir="LTR">&nbsp;</span></p>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'PrivacyPolicy'
}

</script>
