<template>
  <div class="modal fade" id="terms-of-service" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">الشروط و الأحكام</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>تشكل شروط الاستخدام هذه اتفاقية ملزمة قانونًا بينك ، سواء شخصيًا أو نيابةً عن كيان و شركة ميزا و خدمات يوني فيما يتعلق بوصولك إلى موقع الويب و / أو تطبيق الهاتف المحمول للخدمة أو اي وسائل اخرى تتم استخدامه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت توافق على أنه بدخولك إلى الموقع ، تكون قد قرأت وفهمت وتوافق على الالتزام بجميع شروط الاستخدام هذه ، إذا كنت لا توافق على جميع شروط الاستخدام هذه ، فأنت ممنوع صراحة من استخدام الموقع و يجب عليك التوقف عن الاستخدام على الفور.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>سننبهك بشأن أي تغييرات عن طريق تحديث تاريخ &quot;آخر تحديث&quot; لشروط الاستخدام هذه ، وتتنازل عن أي حق لتلقي إشعار محدد لكل تغيير من هذا القبيل.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>تقع على عاتقك مسؤولية المراجعة الدورية لشروط الاستخدام هذه للبقاء على اطلاع على التحديثات. ستخضع وستُعتبر أنك قد علمت وقبلت التغييرات في أي شروط استخدام منقحة من خلال استمرار استخدامك للموقع بعد تاريخ نشر شروط الاستخدام المعدلة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>المعلومات المقدمة على الموقع غير مخصصة للتوزيع أو الاستخدام من قبل أي شخص أو كيان في أي ولاية قضائية أو دولة يكون فيها هذا التوزيع أو الاستخدام مخالفًا للقانون أو اللوائح أو التي ستخضعنا لأي متطلبات تسجيل داخل هذه الولاية أو الدولة .</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>وبناءً على ذلك ، فإن الأشخاص الذين يختارون الوصول إلى الموقع من مواقع أخرى يفعلون ذلك بمبادرة منهم وهم وحدهم المسؤولون عن الامتثال للقوانين المحلية ، إذا كانت القوانين المحلية قابلة للتطبيق وإلى الحد.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><strong><span style='font-size:25px;font-family:"Arial",sans-serif;'>تمثيلات المستخدم</span></strong><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>باستخدام الموقع ، فإنك تقر وتضمن ما يلي:</span>&nbsp;</p>
          <ul style="list-style-type: disc;">
            <li><span style='font-family:"Arial",sans-serif;'>ستكون جميع معلومات التسجيل التي ترسلها صحيحة ودقيقة وحديثة وكاملة ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>ستحافظ على دقة هذه المعلومات وتقوم بتحديث معلومات التسجيل فورًا حسب الضرورة ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>لديك الأهلية القانونية وتوافق على الامتثال لشروط الاستخدام هذه ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>أنت لست تحت سن 18 سنوات.&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>لن تتمكن من الوصول إلى الموقع من خلال وسائل آلية أو غير بشرية ، سواء من خلال الروبوت أو البرنامج النصي أو غير ذلك ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>لن تستخدم الموقع لأي غرض غير قانوني أو غير مصرح به ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>إن استخدامك للموقع لن ينتهك أي قانون أو لائحة معمول بها.&nbsp;</span></li>
          </ul>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>الشروط والأحكام أو المستندات التكميلية التي قد يتم نشرها على الموقع من وقت لآخر مدرجة هنا صراحةً كمرجع. نحن نحتفظ بالحق ، وفقًا لتقديرنا الخاص ، في إجراء تغييرات أو تعديلات على شروط الاستخدام هذه في أي وقت ولأي سبب.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>تسجيل المستخدم</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت مطالب بالتسجيل في الموقع. أنت توافق على الحفاظ على سرية كلمة المرور الخاصة بك وستكون مسؤولاً عن كل استخدام لحسابك وكلمة المرور. نحتفظ بالحق في إزالة اسم مستخدم تحدده أو استعادته أو تغييره إذا قررنا ، وفقًا لتقديرنا الخاص ، أن اسم المستخدم هذا غير لائق أو فاحش أو مرفوض بأي شكل آخر.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>منتجات</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>[نحن نبذل قصارى جهدنا لعرض ألوان وميزات ومواصفات وتفاصيل المنتجات المتوفرة على الموقع بأكبر قدر ممكن من الدقة. ومع ذلك ، نحن لا نضمن أن تكون الألوان والميزات والمواصفات وتفاصيل المنتجات دقيقة أو كاملة أو موثوقة أو حديثة أو خالية من الأخطاء الأخرى ، وقد لا تعكس الشاشة الإلكترونية بدقة الألوان والتفاصيل الفعلية منتجات.]</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>تخضع جميع المنتجات للتوافر [، ولا يمكننا ضمان أن العناصر ستكون في المخزون]. نحتفظ بالحق في إيقاف أي منتجات في أي وقت ولأي سبب. تخضع أسعار جميع المنتجات للتغيير.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>المشتريات والدفع</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نقبل طرق الدفع التالية:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>1- الدفع بإستخدام يوني.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت توافق على تقديم معلومات الشراء والحساب الحالية والكاملة والدقيقة لجميع عمليات الشراء التي تتم عبر الموقع. أنت توافق أيضًا على تحديث معلومات الحساب والدفع على الفور ، بما في ذلك عنوان البريد الإلكتروني ، وطريقة الدفع ، حتى نتمكن من إكمال معاملاتك والاتصال بك حسب الحاجة. سيتم إضافة ضريبة المبيعات. قد نغير الأسعار في أي وقت.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحتفظ بالحق في رفض أي طلب يتم تقديمه عبر الموقع. يجوز لنا ، وفقًا لتقديرنا الخاص ، تحديد أو إلغاء الكميات المشتراة لكل شخص أو لكل أسرة أو لكل طلب. قد تتضمن هذه القيود الطلبات المقدمة من قبل أو تحت حساب العميل نفسه ، و / أو طريقة الدفع نفسها ، و / أو الطلبات التي تستخدم نفس العنوان. نحن نحتفظ بالحق في تقييد أو حظر الطلبات التي ، وفقًا لتقديرنا الخاص ، تظهر من قبل التجار أو البائعين أو الموزعين.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>الأنشطة المحظورة</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يجوز لك الوصول إلى الموقع أو استخدامه لأي غرض بخلاف الغرض الذي نجعل الموقع متاحًا من أجله. لا يجوز استخدام الموقع فيما يتعلق بأي مساعي تجارية باستثناء تلك التي نؤيدها أو نوافق عليها بشكل خاص.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>بصفتك مستخدمًا للموقع ، فإنك توافق على عدم:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>1- استرجاع البيانات أو المحتوى الآخر بشكل منهجي من الموقع لإنشاء أو تجميع ، بشكل مباشر أو غير مباشر ، مجموعة أو تصنيف أو قاعدة بيانات أو دليل دون إذن كتابي منا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>2- التحايل على ميزات الموقع المتعلقة بالأمان أو تعطيلها أو التدخل فيها بأي شكل آخر ، بما في ذلك الميزات التي تمنع أو تقيد استخدام أو نسخ أي محتوى أو تفرض قيودًا على استخدام الموقع و / أو المحتوى الوارد فيه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>3- الانخراط في تأطير أو ربط غير مصرح به للموقع.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>4- استخدام خدمات الدعم الخاصة بنا بشكل غير صحيح أو تقديم تقارير كاذبة عن إساءة أو سوء سلوك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>5- الانخراط في أي استخدام آلي للنظام ، مثل استخدام البرامج النصية لإرسال التعليقات أو الرسائل ، أو استخدام أي استخراج للبيانات ، أو الروبوتات ، أو أدوات مماثلة لجمع البيانات واستخراجها.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>6- التدخل في أو تعطيل أو إنشاء عبء غير ضروري على الموقع أو الشبكات أو الخدمات المتصلة بالموقع.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>7- بيع أو نقل ملفك الشخصي.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>8- استخدام الموقع كجزء من أي جهد للتنافس معنا أو استخدام الموقع و / أو المحتوى بأي طريقة أخرى لأي محاولة مدرة للدخل أو مشروع تجاري.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>9- فك أو فك أو تفكيك أو إجراء هندسة عكسية لأي من البرامج التي تتكون أو تشكل بأي شكل من الأشكال جزءًا من الموقع.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>10- محاولة تجاوز أي تدابير في الموقع مصممة لمنع أو تقييد الوصول إلى الموقع ، أو أي جزء من الموقع.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>11- مضايقة أو إزعاج أو تخويف أو تهديد أي من موظفينا أو وكلائنا العاملين في تقديم أي جزء من الموقع لك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>12- نسخ أو تكييف برامج الموقع ، بما في ذلك على سبيل المثال لا الحصر&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Flash</span><span style='font-family:"Arial",sans-serif;'>&nbsp;،&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>PHP&nbsp;</span><span style='font-family:"Arial",sans-serif;'>،&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>HTML&nbsp;</span><span style='font-family:"Arial",sans-serif;'>،&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>JavaScript</span><span style='font-family:"Arial",sans-serif;'>&nbsp;، أو غيرها من التعليمات البرمجية.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>13- تحميل أو إرسال (أو محاولة تحميل أو إرسال) أي مادة تعمل كآلية جمع أو نقل معلومات سلبية أو نشطة ، بما في ذلك على سبيل المثال لا الحصر ، تنسيقات تبادل الرسومات الواضحة&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>(&quot;gifs&quot;)&nbsp;</span><span style='font-family:"Arial",sans-serif;'>، 1&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>&times; 1</span><span style='font-family:"Arial",sans-serif;'>&nbsp;بكسل ، أخطاء الويب أو ملفات تعريف الارتباط أو أجهزة أخرى مماثلة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>14- استخدام الموقع بطريقة لا تتوافق مع أي قوانين أو لوائح معمول بها.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>إرشادات للمراجعات</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نوفر لك مناطق على الموقع لترك التقييمات أو التقييمات. عند نشر مراجعة ، يجب أن تلتزم بالمعايير التالية:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(1) يجب أن تكون لديك خبرة مباشرة مع الشخص / الكيان الذي تتم مراجعته ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(2) يجب ألا تحتوي تعليقاتك على لغة بذيئة مسيئة أو لغة مسيئة أو عنصرية أو مسيئة أو تحض على الكراهية ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(3) يجب ألا تحتوي مراجعاتك على مراجع تمييزية على أساس الدين أو العرق أو الجنس أو الأصل القومي أو العمر أو الحالة الاجتماعية أو التوجه الجنسي أو الإعاقة ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(4) يجب ألا تحتوي مراجعاتك على إشارات إلى نشاط غير قانوني ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(5) يجب ألا تنتسب إلى المنافسين في حالة نشر مراجعات سلبية ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(6) لا يجب أن تتوصل إلى أي استنتاجات بشأن شرعية السلوك ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(7) لا يجوز لك نشر أي بيانات كاذبة أو مضللة ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(8) لا يجوز لك تنظيم حملة لتشجيع الآخرين على نشر المراجعات سواء كانت إيجابية أو سلبية.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد نقبل أو نرفض أو نزيل المراجعات وفقًا لتقديرنا الخاص. ليس لدينا أي التزام على الإطلاق بفحص المراجعات أو حذف المراجعات ، حتى إذا اعتبر أي شخص أن المراجعات مرفوضة أو غير دقيقة. لا نوافق على المراجعات ولا تمثل بالضرورة آراءنا أو آراء أي من الشركات التابعة لنا أو شركائنا.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحن لا نتحمل المسؤولية عن أي مراجعة أو عن أي مطالبات أو التزامات أو خسائر ناتجة عن أي مراجعة. من خلال نشر مراجعة ، فإنك تمنحنا بموجب هذا حقًا وترخيصًا دائمًا ، وغير حصريًا ، وعالميًا ، وخاليًا من حقوق الملكية ، ومدفوعًا بالكامل ، وقابلًا للتنازل ، ومرخصًا من الباطن لإعادة إنتاج وتعديل وترجمة ونقل بأي وسيلة و / أو توزيع كل المحتوى المتعلق بالمراجعات.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>رخصة تطبيق جوال</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>استخدام الترخيص</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>إذا قمت بالوصول إلى الموقع عبر تطبيق محمول ، فإننا نمنحك حقًا قابلاً للإلغاء وغير حصري وغير قابل للتحويل ومحدودًا لتثبيت واستخدام تطبيق الهاتف المحمول على الأجهزة الإلكترونية اللاسلكية التي تمتلكها أو تتحكم فيها ، والوصول إلى واستخدام تطبيق الهاتف المحمول على هذه الأجهزة بما يتفق تمامًا مع أحكام وشروط ترخيص تطبيق الهاتف المحمول الوارد في شروط الاستخدام هذه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يجب عليك:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(1) فك الشفرة أو الهندسة العكسية أو تفكيك أو محاولة اشتقاق شفرة المصدر أو فك تشفير التطبيق ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(2) إجراء أي تعديل أو تكييف أو تحسين أو تحسين أو ترجمة أو عمل مشتق من التطبيق ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(3) تنتهك أي قوانين أو قواعد أو لوائح سارية فيما يتعلق بوصولك أو استخدامك للتطبيق ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(4) إزالة أو تغيير أو طمس أي إشعار ملكية (بما في ذلك أي إشعار بحقوق النشر أو العلامة التجارية) تم نشره من قبلنا أو من قبل الجهات المرخصة للتطبيق ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(5) استخدام التطبيق في أي محاولة مدرة للدخل أو مشروع تجاري أو أي غرض آخر لم يتم تصميمه أو الغرض منه.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(6) إتاحة التطبيق عبر شبكة أو بيئة أخرى تسمح بالوصول أو الاستخدام بواسطة أجهزة أو مستخدمين متعددين في نفس الوقت ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(7) استخدام التطبيق لإنشاء منتج أو خدمة أو برنامج يكون ، بشكل مباشر أو غير مباشر ، منافسًا أو بديلاً للتطبيق بأي شكل من الأشكال ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(8) استخدام التطبيق لإرسال استعلامات تلقائية إلى أي موقع ويب أو لإرسال أي بريد إلكتروني تجاري غير مرغوب فيه ؛</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(9) استخدام أي معلومات ملكية أو أي من واجهاتنا أو ملكيتنا الفكرية الأخرى في تصميم أو تطوير أو تصنيع أو ترخيص أو توزيع أي تطبيقات أو ملحقات أو أجهزة للاستخدام مع التطبيق.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>أجهزة&nbsp;</span></strong><strong><span dir="LTR" style='font-size:20px;font-family:"Arial",sans-serif;'>Apple</span></strong><strong><span style='font-size:20px;font-family:"Arial",sans-serif;'>&nbsp;و&nbsp;</span></strong><strong><span dir="LTR" style='font-size:20px;font-family:"Arial",sans-serif;'>Android</span></strong><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>تنطبق الشروط التالية عند استخدام تطبيق جوال تم الحصول عليه من متجر&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Apple</span><span style='font-family:"Arial",sans-serif;'>&nbsp;أو&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Google Play (</span><span style='font-family:"Arial",sans-serif;'>كل &quot;موزع تطبيقات&quot;) للوصول إلى الموقع:</span>&nbsp;</p>
          <ul style="list-style-type: disc;">
            <li><span style='font-family:"Arial",sans-serif;'>يقتصر الترخيص الممنوح لك لتطبيق الهاتف المحمول الخاص بنا على ترخيص غير قابل للتحويل لاستخدام التطبيق على جهاز يستخدم نظام التشغيل&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Apple iOS</span><span style='font-family:"Arial",sans-serif;'>&nbsp;أو&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>Android</span><span style='font-family:"Arial",sans-serif;'>&nbsp;، حسب الاقتضاء ، ووفقًا لقواعد الاستخدام المنصوص عليها في التطبيق المعمول به شروط خدمة الموزع ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>نحن مسؤولون عن تقديم أي خدمات صيانة ودعم فيما يتعلق بتطبيق الهاتف المحمول كما هو محدد في شروط وأحكام ترخيص تطبيق الهاتف المحمول الوارد في شروط الاستخدام هذه أو كما هو مطلوب بطريقة أخرى بموجب القانون المعمول به ، وأنت تقر بأن كل موزع تطبيق لديه لا يوجد أي التزام على الإطلاق لتقديم أي خدمات صيانة ودعم فيما يتعلق بتطبيق الهاتف المحمول ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>في حالة فشل أي تطبيق جوّال في الامتثال لأي ضمان ساري ، يجوز لك إخطار موزع التطبيق المعمول به ، ويجوز لموزع التطبيق ، وفقًا لشروطه وسياساته ، رد سعر الشراء ، إن وجد ، المدفوع مقابل تطبيق الهاتف المحمول ، وإلى أقصى حد يسمح به القانون المعمول به ، لن يكون على موزع التطبيق أي التزام بالضمان على الإطلاق فيما يتعلق بتطبيق الهاتف المحمول ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>يجب عليك الامتثال لشروط اتفاقية الطرف الثالث المعمول بها عند استخدام تطبيق الهاتف المحمول ، على سبيل المثال ، إذا كان لديك تطبيق&nbsp;</span><span dir="LTR" style='font-family:"Arial",sans-serif;'>VoIP</span><span style='font-family:"Arial",sans-serif;'>&nbsp;، فيجب ألا تنتهك اتفاقية خدمة البيانات اللاسلكية الخاصة بهم عند استخدام تطبيق الهاتف المحمول ؛&nbsp;</span></li>
            <li><span style='font-family:"Arial",sans-serif;'>أنت تقر وتوافق على أن موزعي التطبيقات هم مستفيدون من أطراف ثالثة للشروط والأحكام الواردة في رخصة تطبيقات الهاتف المحمول الواردة في شروط الاستخدام هذه ، وأن كل موزع تطبيق سيكون له الحق (وسيتم اعتباره قد قبل الحق) لفرض الشروط والأحكام الواردة في ترخيص تطبيقات الهاتف المحمول الواردة في شروط الاستخدام هذه ضدك بصفتك مستفيدًا من أطراف ثالثة.&nbsp;</span></li>
          </ul>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><strong><span style='font-size:25px;font-family:"Arial",sans-serif;'>وسائل الإعلام الاجتماعية</span></strong><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>كجزء من وظائف الموقع ، يمكنك ربط حسابك بالحسابات عبر الإنترنت التي لديك مع موفري خدمة من جهات خارجية عن طريق إما:</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>(1) تقديم معلومات تسجيل الدخول إلى حساب الطرف الثالث من خلال الموقع ؛ أو (2) السماح لنا بالوصول إلى حساب الطرف الثالث الخاص بك ، كما هو مسموح به بموجب الشروط والأحكام المعمول بها والتي تحكم استخدامك لكل حساب طرف ثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت تقر وتضمن أنه يحق لك الكشف عن معلومات تسجيل الدخول إلى حساب الطرف الثالث الخاص بك لنا و / أو منحنا حق الوصول إلى حساب الطرف الثالث الخاص بك ، دون انتهاكك لأي من الشروط والأحكام التي تحكم استخدامك للتطبيق حساب الطرف الثالث ، ودون إلزامنا بدفع أي رسوم أو إخضاعنا لقيود الاستخدام التي يفرضها مقدم خدمة الطرف الثالث لحساب الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>من خلال منحنا حق الوصول إلى أي حسابات لجهات خارجية ، فأنت تدرك أنه (1) يجوز لنا الوصول إلى أي محتوى قمت بتوفيره وتخزينه (إن أمكن) وتخزينه في حساب الطرف الثالث (&quot;الشبكة الاجتماعية&quot; المحتوى &quot;) بحيث يكون متاحًا على الموقع وعبره عبر حسابك ، بما في ذلك على سبيل المثال لا الحصر ، أي قوائم أصدقاء و (2) قد نقوم بإرسال معلومات إضافية إلى حساب الطرف الثالث وتلقيها إلى الحد الذي يتم إعلامك به عند الربط حسابك مع حساب الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>اعتمادًا على حسابات الطرف الثالث التي تختارها وتخضع لإعدادات الخصوصية التي قمت بتعيينها في حسابات الطرف الثالث ، قد تكون معلومات التعريف الشخصية التي تنشرها في حسابات الطرف الثالث متاحة على حسابك ومن خلاله على الموقع. يرجى ملاحظة أنه إذا أصبح حساب الطرف الثالث أو الخدمة المرتبطة به غير متوفر أو تم إنهاء وصولنا إلى حساب الطرف الثالث هذا من قبل مزود خدمة الطرف الثالث ، فقد لا يكون محتوى الشبكة الاجتماعية متاحًا على الموقع ومن خلاله.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>ستتمكن من تعطيل الاتصال بين حسابك على الموقع وحسابات الطرف الثالث في أي وقت. الرجاء ملاحظة أن علاقتك مع موفري خدمة الأطراف الثالثة المرتبطين بحسابك الخاص بالطرف الثالث يتم إجراؤها فقط بموجب الاتفاقية (الاتفاقات) الخاصة بك مع موفري خدمة الأطراف الثالثة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحن لا نبذل أي جهد لمراجعة أي محتوى للشبكة الاجتماعية لأي غرض ، بما في ذلك على سبيل المثال لا الحصر ، الدقة أو الشرعية أو عدم الانتهاك ، ولسنا مسؤولين عن أي محتوى للشبكة الاجتماعية. أنت تقر وتوافق على أنه يجوز لنا الوصول إلى دفتر عناوين بريدك الإلكتروني المرتبط بحساب جهة خارجية وقائمة جهات الاتصال الخاصة بك المخزنة على جهازك المحمول أو الكمبيوتر اللوحي فقط لأغراض تحديد وإبلاغك بجهات الاتصال التي سجلت أيضًا لاستخدام الموقع .</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يمكنك إلغاء تنشيط الاتصال بين الموقع وحساب الطرف الثالث الخاص بك عن طريق الاتصال بنا باستخدام معلومات الاتصال أدناه أو من خلال إعدادات حسابك (إن وجدت). سنحاول حذف أي معلومات مخزنة على خوادمنا تم الحصول عليها من خلال حساب الطرف الثالث ، باستثناء اسم المستخدم وصورة الملف الشخصي التي أصبحت مرتبطة بحسابك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>الطلبات</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت تقر وتوافق على أن أي أسئلة أو تعليقات أو اقتراحات أو أفكار أو تعليقات أو معلومات أخرى تتعلق بالموقع (&quot;التقديمات&quot;) التي تقدمها لنا غير سرية وستصبح ملكنا الوحيد. يجب أن نمتلك حقوقًا حصرية ، بما في ذلك جميع حقوق الملكية الفكرية ، ويحق لنا الاستخدام غير المقيد ونشر هذه التقديمات لأي غرض قانوني ، تجاري أو غير ذلك ، دون الاعتراف أو التعويض لك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت بموجب هذه الاتفاقية تتنازل عن جميع الحقوق المعنوية لأي من هذه التقديمات ، وتضمن بموجب هذا أن أي من هذه التقديمات أصلية معك أو أن لديك الحق في تقديم مثل هذه التقديمات. أنت توافق على أنه لن يكون هناك حق الرجوع ضدنا لأي انتهاك مزعوم أو فعلي أو اختلاس لأي حق من حقوق الملكية في عمليات الإرسال الخاصة بك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>مواقع الويب والمحتويات الخاصة بأطراف أخرى</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد يحتوي الموقع (أو قد يتم إرسالك عبر الموقع) على روابط لمواقع أخرى (&quot;مواقع الطرف الثالث&quot;) بالإضافة إلى المقالات والصور والنصوص والرسومات والصور والتصميمات والموسيقى والصوت والفيديو والمعلومات والتطبيقات والبرامج والمحتويات أو العناصر الأخرى التي تخص أو تنشأ من أطراف ثالثة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يتم التحقيق في مواقع الطرف الثالث ومحتويات الطرف الثالث أو مراقبتها أو التحقق منها للتأكد من دقتها أو ملاءمتها أو اكتمالها ، كما أننا لسنا مسؤولين عن أي مواقع ويب لطرف ثالث يتم الوصول إليها عبر الموقع أو أي محتوى لطرف ثالث منشور على ، متوفرة من خلال الموقع أو مثبتة عليه ، بما في ذلك المحتوى ، أو الدقة ، أو العدوانية ، أو الآراء ، أو الموثوقية ، أو ممارسات الخصوصية ، أو السياسات الأخرى أو المضمنة في مواقع الطرف الثالث أو محتوى الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يعني تضمين أو ربط أو السماح باستخدام أو تثبيت أي مواقع ويب تابعة لطرف ثالث أو أي محتوى تابع لطرف ثالث الموافقة أو المصادقة عليها من قبلنا. إذا قررت مغادرة الموقع والوصول إلى مواقع الطرف الثالث أو استخدام أو تثبيت أي محتوى لطرف ثالث ، فإنك تفعل ذلك على مسؤوليتك الخاصة ، ويجب أن تكون على علم بأن شروط الاستخدام هذه لم تعد تحكم.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يجب عليك مراجعة الشروط والسياسات المعمول بها ، بما في ذلك ممارسات الخصوصية وجمع البيانات ، لأي موقع ويب تنتقل إليه من الموقع أو تتعلق بأي تطبيقات تستخدمها أو تثبتها من الموقع. أي مشتريات تقوم بها من خلال مواقع الطرف الثالث ستكون عبر مواقع أخرى ومن شركات أخرى ، ولا نتحمل أي مسؤولية على الإطلاق فيما يتعلق بمثل هذه المشتريات التي تكون حصريًا بينك وبين الطرف الثالث المعمول به.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت توافق وتقر بأننا لا نؤيد المنتجات أو الخدمات المقدمة على مواقع الطرف الثالث وعليك أن تجعلنا غير مؤذيين من أي ضرر ناتج عن شرائك لهذه المنتجات أو الخدمات. بالإضافة إلى ذلك ، يجب عليك أن تجعلنا غير مؤذيين من أي خسائر تتكبدها أو تضرر منك فيما يتعلق أو ينتج بأي شكل من الأشكال عن أي محتوى لطرف ثالث أو أي اتصال بمواقع الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>[عدل]</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;'><span style='font-size:25px;font-family:"Arial",sans-serif;'>وسائل الإعلام الاجتماعية</span><span style="font-size:25px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>كجزء من وظائف الموقع ، يمكنك ربط حسابك بالحسابات عبر الإنترنت التي لديك مع مزودي خدمة من جهات خارجية (كل حساب من هذا القبيل ، &quot;حساب طرف ثالث&quot;) إما عن طريق: (1) توفير حساب الطرف الثالث معلومات تسجيل الدخول من خلال الموقع ؛ أو (2) السماح لنا بالوصول إلى حساب الطرف الثالث الخاص بك ، كما هو مسموح به بموجب الشروط والأحكام المعمول بها والتي تحكم استخدامك لكل حساب طرف ثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت تقر وتضمن أنه يحق لك الكشف عن معلومات تسجيل الدخول إلى حساب الطرف الثالث الخاص بك لنا و / أو منحنا حق الوصول إلى حساب الطرف الثالث الخاص بك ، دون انتهاكك لأي من الشروط والأحكام التي تحكم استخدامك للتطبيق حساب الطرف الثالث ، ودون إلزامنا بدفع أي رسوم أو إخضاعنا لقيود الاستخدام التي يفرضها مقدم خدمة الطرف الثالث لحساب الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>من خلال منحنا حق الوصول إلى أي حسابات لجهات خارجية ، فأنت تدرك أنه (1) يجوز لنا الوصول إلى أي محتوى قمت بتوفيره وتخزينه (إن أمكن) وتخزينه في حساب الطرف الثالث (&quot;الشبكة الاجتماعية&quot; المحتوى &quot;) بحيث يكون متاحًا على الموقع وعبره عبر حسابك ، بما في ذلك على سبيل المثال لا الحصر ، أي قوائم أصدقاء و (2) قد نقوم بإرسال معلومات إضافية إلى حساب الطرف الثالث وتلقيها إلى الحد الذي يتم إعلامك به عند الربط حسابك مع حساب الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>اعتمادًا على حسابات الطرف الثالث التي تختارها وتخضع لإعدادات الخصوصية التي قمت بتعيينها في حسابات الطرف الثالث ، قد تكون معلومات التعريف الشخصية التي تنشرها في حسابات الطرف الثالث متاحة على حسابك ومن خلاله على الموقع. يرجى ملاحظة أنه إذا أصبح حساب الطرف الثالث أو الخدمة المرتبطة به غير متوفر أو تم إنهاء وصولنا إلى حساب الطرف الثالث هذا من قبل مزود خدمة الطرف الثالث ، فقد لا يكون محتوى الشبكة الاجتماعية متاحًا على الموقع ومن خلاله.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>ستتمكن من تعطيل الاتصال بين حسابك على الموقع وحسابات الطرف الثالث في أي وقت. الرجاء ملاحظة أن علاقتك مع موفري خدمة الأطراف الثالثة المرتبطين بحسابك الخاص بالطرف الثالث يتم إجراؤها فقط بموجب الاتفاقية (الاتفاقات) الخاصة بك مع موفري خدمة الأطراف الثالثة.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>نحن لا نبذل أي جهد لمراجعة أي محتوى للشبكة الاجتماعية لأي غرض ، بما في ذلك على سبيل المثال لا الحصر ، الدقة أو الشرعية أو عدم الانتهاك ، ولسنا مسؤولين عن أي محتوى للشبكة الاجتماعية. أنت تقر وتوافق على أنه يجوز لنا الوصول إلى دفتر عناوين بريدك الإلكتروني المرتبط بحساب جهة خارجية وقائمة جهات الاتصال الخاصة بك المخزنة على جهازك المحمول أو الكمبيوتر اللوحي فقط لأغراض تحديد وإبلاغك بجهات الاتصال التي سجلت أيضًا لاستخدام الموقع .</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يمكنك إلغاء تنشيط الاتصال بين الموقع وحساب الطرف الثالث الخاص بك عن طريق الاتصال بنا باستخدام معلومات الاتصال أدناه أو من خلال إعدادات حسابك (إن وجدت). سنحاول حذف أي معلومات مخزنة على خوادمنا تم الحصول عليها من خلال حساب الطرف الثالث ، باستثناء اسم المستخدم وصورة الملف الشخصي التي أصبحت مرتبطة بحسابك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-size:20px;font-family:"Arial",sans-serif;'>الطلبات</span><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت تقر وتوافق على أن أي أسئلة أو تعليقات أو اقتراحات أو أفكار أو تعليقات أو معلومات أخرى تتعلق بالموقع (&quot;التقديمات&quot;) التي تقدمها لنا غير سرية وستصبح ملكنا الوحيد. يجب أن نمتلك حقوقًا حصرية ، بما في ذلك جميع حقوق الملكية الفكرية ، ويحق لنا الاستخدام غير المقيد ونشر هذه التقديمات لأي غرض قانوني ، تجاري أو غير ذلك ، دون الاعتراف أو التعويض لك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت بموجب هذه الاتفاقية تتنازل عن جميع الحقوق المعنوية لأي من هذه التقديمات ، وتضمن بموجب هذا أن أي من هذه التقديمات أصلية معك أو أن لديك الحق في تقديم مثل هذه التقديمات. أنت توافق على أنه لن يكون هناك حق الرجوع ضدنا لأي انتهاك مزعوم أو فعلي أو اختلاس لأي حق من حقوق الملكية في عمليات الإرسال الخاصة بك.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>[عدل]</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-size:20px;font-family:"Arial",sans-serif;'>مواقع الويب والمحتويات الخاصة بأطراف أخرى</span><span style="font-size:20px;">&nbsp;</span></p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>قد يحتوي الموقع (أو قد يتم إرسالك عبر الموقع) على روابط لمواقع أخرى (&quot;مواقع الطرف الثالث&quot;) بالإضافة إلى المقالات والصور والنصوص والرسومات والصور والتصميمات والموسيقى والصوت والفيديو والمعلومات والتطبيقات والبرامج والمحتويات أو العناصر الأخرى التي تخص أو تنشأ من أطراف ثالثة (&quot;محتوى الأطراف الثالثة&quot;).</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يتم التحقيق في مواقع الويب الخاصة بهذه الأطراف ومحتوياتها أو مراقبتها أو التحقق منها للتأكد من دقتها أو ملاءمتها أو اكتمالها ، كما أننا لسنا مسؤولين عن أي مواقع ويب تابعة لطرف ثالث يتم الوصول إليها عبر الموقع أو أي محتوى لطرف ثالث منشور على ، متوفرة من خلال الموقع أو مثبتة عليه ، بما في ذلك المحتوى ، أو الدقة ، أو العدوانية ، أو الآراء ، أو الموثوقية ، أو ممارسات الخصوصية ، أو السياسات الأخرى أو المضمنة في مواقع الطرف الثالث أو محتوى الطرف الثالث.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>لا يعني تضمين أو ربط أو السماح باستخدام أو تثبيت أي مواقع ويب تابعة لطرف ثالث أو أي محتوى تابع لطرف ثالث الموافقة أو المصادقة عليها من قبلنا. إذا قررت مغادرة الموقع والوصول إلى مواقع الطرف الثالث أو استخدام أو تثبيت أي محتوى لطرف ثالث ، فإنك تفعل ذلك على مسؤوليتك الخاصة ، ويجب أن تكون على علم بأن شروط الاستخدام هذه لم تعد تحكم.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>يجب عليك مراجعة الشروط والسياسات المعمول بها ، بما في ذلك ممارسات الخصوصية وجمع البيانات ، لأي موقع ويب تنتقل إليه من الموقع أو تتعلق بأي تطبيقات تستخدمها أو تثبتها من الموقع. أي مشتريات تقوم بها من خلال مواقع الطرف الثالث ستكون عبر مواقع أخرى ومن شركات أخرى ، ولا نتحمل أي مسؤولية على الإطلاق فيما يتعلق بمثل هذه المشتريات التي تكون حصريًا بينك وبين الطرف الثالث المعمول به.</span>&nbsp;</p>
          <p dir="RTL" style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;text-align:right;line-height:18.0pt;'><span style='font-family:"Arial",sans-serif;'>أنت توافق وتقر بأننا لا نؤيد المنتجات أو الخدمات المقدمة على مواقع الطرف الثالث وعليك أن تجعلنا غير مؤذيين من أي ضرر ناتج عن شرائك لهذه المنتجات أو الخدمات. بالإضافة إلى ذلك ، يجب عليك أن تجعلنا غير مؤذيين من أي خسائر تتكبدها أو تضرر منك فيما يتعلق أو ينتج بأي شكل من الأشكال عن أي محتوى لطرف ثالث أو أي اتصال بمواقع الطرف الثالث.</span>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:right;'><strong><span style='font-size:37px;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
          <p dir="RTL" style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:right;'><span dir="LTR">&nbsp;</span></p>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'TermsOfService'
}

</script>
